Repository PhoenixErgo/phoenix-hodlcoin-contracts, pull requests merged in 2023-08, with the labels that each got.

#11 fix bank withdraw condition
  contracts/bank_contract/v1/ergoscript/phoenix_v1_hodlcoin_bank.es
Labels: enhancement

#13 Adjust fee contract
  README.md
  contracts/phoenix_fee_contract/v1/README.md
  contracts/phoenix_fee_contract/v1/docs/phoenix_fee_distribution.pdf
  contracts/phoenix_fee_contract/v1/ergoscript/phoenix_v1_hodlcoin_fee.es
  contracts/proxy_contract/v1/README.md
  docs/Phoenix Hodl Coin Protocol Diagrams.png
  docs/phoenix_hodlerg_protocol_diagrams.png
Labels: documentation, enhancement

#14 Contract: Change kras address
  contracts/phoenix_fee_contract/v1/ergoscript/phoenix_v1_hodlcoin_fee.es
Labels: documentation

#15 remove miner fee check for proxy refunds
  hodlERG/contracts/proxy_contract/v1/ergoscript/phoenix_v1_hodlcoin_proxy.es
Labels: enhancement

#17 Contracts: Fix proxy txOperatorFee
  hodlERG/contracts/proxy_contract/v1/README.md
  hodlERG/contracts/proxy_contract/v1/ergoscript/phoenix_v1_hodlcoin_proxy.es
Labels: enhancement

#21 Hodltoken proxy contract
  hodlERG/contracts/bank_contract/v1/README.md
  hodlERG/contracts/bank_contract/v1/ergoscript/phoenix_v1_hodlerg_bank.es
  hodlERG/contracts/phoenix_fee_contract/v1/README.md
  hodlERG/contracts/phoenix_fee_contract/v1/ergoscript/phoenix_v1_hodlerg_fee.es
  hodlERG/contracts/proxy_contract/v1/README.md
  hodlERG/contracts/proxy_contract/v1/ergoscript/phoenix_v1_hodlerg_proxy.es
  hodlToken/README.md
  hodlToken/contracts/bank_contract/v1/README.md
  hodlToken/contracts/bank_contract/v1/ergoscript/phoenix_v1_hodltoken_bank.es
  hodlToken/contracts/phoenix_fee_contract/v1/README.md
  hodlToken/contracts/phoenix_fee_contract/v1/ergoscript/phoenix_v1_hodltoken_fee.es
  hodlToken/contracts/proxy_contract/v1/README.md
  hodlToken/contracts/proxy_contract/v1/ergoscript/phoenix_v1_hodltoken_proxy.es
Labels: documentation, enhancement

#23 fix usage of value instead of base token
  hodlERG/contracts/proxy_contract/v1/ergoscript/phoenix_v1_hodlerg_proxy.es
  hodlToken/contracts/bank_contract/v1/ergoscript/phoenix_v1_hodltoken_bank.es
  hodlToken/contracts/proxy_contract/v1/README.md
  hodlToken/contracts/proxy_contract/v1/ergoscript/phoenix_v1_hodltoken_proxy.es
Labels: documentation, enhancement

#24 refactor, add baseToken as constant, fix bruno address, fix HOFs
  hodlERG/contracts/proxy_contract/v1/README.md
  hodlToken/contracts/phoenix_fee_contract/v1/README.md
  hodlToken/contracts/phoenix_fee_contract/v1/ergoscript/phoenix_v1_hodltoken_fee.es
  hodlToken/contracts/proxy_contract/v1/README.md
Labels: documentation, enhancement
